<?php

/**
 * Implements hook_field_formatter_info()
 * @return array
 */
function image_single_field_formatter_info() {
  return array(
    'image_single' => array(
      'label' => t('Single image'),
      'field types' => array('image'),
      'settings' => array(
        'image_style' => NULL,
        'link' => NULL,
      ),
    )
  );
}

/**
 * Implements hook_field_formatter_settings_form()
 * @param $field
 * @param $instance
 * @param $view_mode
 * @param $form
 * @param $form_state
 * @return array
 */
function image_single_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();

  if ($display['type'] == 'image_single') {

    $element['image_style'] = array(
      '#title' => t('Main image style'),
      '#type' => 'select',
      '#options' => image_style_options(),
      '#default_value' => $settings['image_style'],
    );

    $element['link'] = array(
      '#title' => t('Link to content'),
      '#type' => 'checkbox',
      '#default_value' => $settings['link'],
    );
  }

  return $element;
}


/**
 * Implements hook_field_formatter_settings_summary()
 * @param $field
 * @param $instance
 * @param $view_mode
 * @return string
 */
function image_single_field_formatter_settings_summary($field, $instance, $view_mode) {
  $settings = $instance['display'][$view_mode]['settings'];
  $options = image_style_options();

  $style = $settings['image_style'];
  $bool = !empty($settings['link']) ? t('Yes') : t('No');

  $lines[] = t('Image style: !style', array('!style' => !empty($style) ? $options[$style] : t('Original')));
  $lines[] = t('Link content: !bool', array('!bool' => $bool));

  return implode('<br />', $lines);
}

/**
 * Implements hook_field_formatter_view()
 * @param $entity_type
 * @param $entities
 * @param $field
 * @param $instances
 * @param $langcode
 * @param $items
 * @param $displays
 * @return mixed
 */
function image_single_field_formatter_view($entity_type, $entities, $field, $instances, $langcode, &$items, $displays) {
  $image = reset($items);
  $settings = $displays['settings'];

  $variables = array(
    'path' => $image['uri'],
    'style_name' => $displays['settings']['image_style'],
    'attributes' => array(),
    'width' => NULL,
    'alt' => !empty($image['alt']) ? $image['alt'] : '',
    'height' => NULL,
  );

  if(isset($settings['link']) && $settings['link']) {
    $entity_uri = entity_uri($entity_type, $entities);
    $content = l(theme_image($variables), $entity_uri['path'], array('html' => TRUE));
  } else {
    $content = theme_image($variables);
  }

  $build[0] = array(
    '#markup' => $content,
  );

  return $build;
}